name: Deploy Daily

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18' # Ou a versão do Node.js que seu projeto requer

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: npm run start

    - name: Deploy
      # Adicione passos específicos para o deploy aqui, dependendo do seu alvo de deploy
