name: Deploy Every 4 Hours

on:
  schedule:
    - cron: '0 */2 * * *' # Executa a cada 4 horas, no início da hora (0 minutos)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Este passo usa a ação 'checkout' para fazer checkout do seu repositório

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Atualizado para Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: npm run start

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

