# name: Deploy Every 2 Hours

# on:
#   schedule:
#     - cron: '*/5 * * * *'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#       # Este passo usa a ação 'checkout' para fazer checkout do seu repositório

#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20' # Ou a versão do Node.js que seu projeto requer

#     - name: Install dependencies
#       run: npm install

#     - name: Run script
#       run: npm run start

#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.Liturgia }}
#         publish_dir: ./

#name: Deploy Every 5 minutes

#on:
 # schedule:
  #  - cron: "*/5 * * * *"

#jobs:
 # build-and-deploy:
  #  runs-on: ubuntu-latest

   # steps:
    #  - uses: actions/checkout@v4

     # - name: Setup Node.js
      #  uses: actions/setup-node@v4
       # with:
        #  node-version: "20"

     # - name: Install dependencies
      #  run: npm install

      #- name: Run script
       # run: npm run start

      #- name: Add Email
       # run: git config --global user.email mateus15do2@gmail.com

      #- name: Add Name
       # run: git config --global user.name Mateus Santos

      #- name: Commit and push changes
      #  run: node script.js

      #- name: Push changes (requires GITHUB_TOKEN secret)
       # run: git push origin HEAD:${{ github.sha }} --force ${{ secrets.GITHUB_TOKEN }}

       name: Node.js Build and Push

       on:
         schedule:
           - cron: '*/5 * * * *' # Executa a cada 5 minutos
       
       jobs:
         build:
           runs-on: ubuntu-latest
       
           steps:
           - name: Checkout repository
             uses: actions/checkout@v4
       
           - name: Setup Node.js
             uses: actions/setup-node@v4
             with:
               node-version: '20'
       
           - name: Install dependencies
             run: npm install
       
           - name: Build
             run: npm run start
       
           - name: Commit and Push Changes
             run: |
               git config --global user.email "mateus15do2@gmail.com"
               git config --global user.name "Mateus Santos"
               git add .
               git commit -m "Autualização Automática]"
               git status
               git push https://${{ secrets.GITHUB_TOKEN }}@github.com/pacdt/Liturgia-diaria.git HEAD:main
       